replicaCount: 1

image:
  repository: rusoil-gpt-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  host: usptu.local

resources: {}
