replicaCount: 1

image:
  repository: petra-gpt-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  host: petra-gpt.local

resources: {}
