apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rusoilgpt.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "rusoilgpt.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "rusoilgpt.name" . }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MODE
              value: "prod"
