apiVersion: apps/v1
kind: Deployment
metadata:
  name: usptu-backend
  labels:
    app: usptu-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usptu-backend
  template:
    metadata:
      labels:
        app: usptu-backend
    spec:
      containers:
        - name: backend
          image: rusoil-gpt-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: MODE
              value: "prod"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: usptu-secrets
                  key: DATABASE_URL
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: usptu-backend-svc
spec:
  selector:
    app: usptu-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
